@echo off
echo Initializing git repository...
git init
echo Adding all files to the staging area...
git add .
echo Configuring user name and email...
git config --global user.name RamesusXD
git config --global user.email j1gamer4life@gmail.com
echo Committing changes...
git commit -m "codeupdates/gitscript"
echo Pushing changes to remote repository...
git push -u origin master
echo Batch script completed successfully.
pause
